volumes:
  redis-data:
  postgres-data:

services:
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql